version: '3.8'

services:
  fastify:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads   # Persist uploaded files
    restart: always
