version: '3.8'

services:
  fastify:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # - .:/app
      # - /app/node_modules
      - ./uploads:/app/uploads   # Persist uploaded files
    restart: always
    # environment:
    #   - NODE_ENV=development
