apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastify-app
  template:
    metadata:
      labels:
        app: fastify-app
    spec:
      containers:
        - name: fastify-app
          image: fastify-app
          ports:
            - containerPort: 3000
